from __future__ import annotations

from typing import Any

def _native_association_mass_action_block(*args: Any, **kwargs: Any) -> Any: ...
def _native_chemical_equilibrium_block(*args: Any, **kwargs: Any) -> Any: ...
def _native_electrolyte_contribution_block(*args: Any, **kwargs: Any) -> Any: ...
def _native_electrolyte_held2_phase_discovery(*args: Any, **kwargs: Any) -> Any: ...
def _native_electrolyte_postsolve_certification(*args: Any, **kwargs: Any) -> Any: ...
def _native_electrolyte_stage_iii_refinement(*args: Any, **kwargs: Any) -> Any: ...
def _native_electrolyte_tpd_phase_discovery(*args: Any, **kwargs: Any) -> Any: ...
def _native_eos_phase_block(*args: Any, **kwargs: Any) -> Any: ...
def _native_eos_phase_system(*args: Any, **kwargs: Any) -> Any: ...
def _native_equilibrium_activation_matrix(*args: Any, **kwargs: Any) -> Any: ...
def _native_equilibrium_activation_plan_contract(*args: Any, **kwargs: Any) -> Any: ...
def _native_equilibrium_selector_contract(*args: Any, **kwargs: Any) -> Any: ...
def _native_equilibrium_selector_route_result(*args: Any, **kwargs: Any) -> Any: ...
def _native_ideal_reaction_smoke(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def _native_ipopt_quadratic_smoke(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def _native_ipopt_smoke(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def _native_neutral_multiphase_eos_nlp_contract(*args: Any, **kwargs: Any) -> Any: ...
def _native_neutral_multiphase_eos_postsolve(*args: Any, **kwargs: Any) -> Any: ...
def _native_neutral_tpd_phase_discovery(*args: Any, **kwargs: Any) -> Any: ...
def _native_neutral_two_phase_eos_nlp_contract(*args: Any, **kwargs: Any) -> Any: ...
def _native_neutral_two_phase_eos_postsolve(*args: Any, **kwargs: Any) -> Any: ...
def _native_neutral_two_phase_eos_result(*args: Any, **kwargs: Any) -> Any: ...
def _native_second_order_assembly_smoke(*args: Any, **kwargs: Any) -> Any: ...
def __getattr__(name: str) -> Any: ...
