from __future__ import annotations

from typing import Any


def _evaluate_generic_native_debug(*args: Any, **kwargs: Any) -> Any: ...
def _fit_generic_native_ceres(*args: Any, **kwargs: Any) -> Any: ...
def _fit_pure_neutral_native_ceres(*args: Any, **kwargs: Any) -> Any: ...
def _fit_pure_neutral_native_debug(*args: Any, **kwargs: Any) -> Any: ...
def _native_ceres_smoke(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def __getattr__(name: str) -> Any: ...
