"""Generate the Python mirror of the native equilibrium activation matrix."""

from __future__ import annotations

import argparse
import importlib.util
import os
import pprint
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.validation import native_freshness

SRC_ROOT = REPO_ROOT / "packages" / "epcsaft" / "src"
OUTPUT = (
    REPO_ROOT
    / "packages"
    / "epcsaft-equilibrium"
    / "src"
    / "epcsaft_equilibrium"
    / "equilibrium_activation.py"
)


def _require_fresh_native_metadata(native_core: object) -> dict[str, object]:
    receipt = native_freshness.build_equilibrium_native_receipt(
        native_module=native_core,
        checker_command=[
            "uv",
            "run",
            "--no-sync",
            "python",
            "scripts/dev/generate_equilibrium_activation.py",
            "--check",
        ],
    )
    try:
        native_freshness.require_equilibrium_native_fresh(receipt)
    except ValueError as exc:
        raise RuntimeError(str(exc)) from exc
    return receipt


def _load_native_metadata() -> tuple[list[dict[str, object]], list[dict[str, object]]]:
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    if str(SRC_ROOT) not in sys.path:
        sys.path.insert(0, str(SRC_ROOT))
    equilibrium_src_root = REPO_ROOT / "packages" / "epcsaft-equilibrium" / "src"
    if str(equilibrium_src_root) not in sys.path:
        sys.path.insert(0, str(equilibrium_src_root))

    from scripts.dev.native_runtime_env import apply_native_runtime_env

    apply_native_runtime_env(os.environ)
    native_candidates = sorted(equilibrium_src_root.glob("epcsaft_equilibrium/_native_core*.so"))
    if len(native_candidates) != 1:
        raise RuntimeError(
            "Expected exactly one built equilibrium native extension before generating "
            f"activation metadata, found {len(native_candidates)}."
        )
    spec = importlib.util.spec_from_file_location("_native_core", native_candidates[0])
    if spec is None or spec.loader is None:
        raise RuntimeError("Unable to load the built equilibrium native extension.")
    native_core = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(native_core)
    _require_fresh_native_metadata(native_core)
    return (
        [dict(row) for row in native_core._native_equilibrium_activation_matrix()],
        [dict(row) for row in native_core._native_equilibrium_selector_route_contracts()],
    )


def _render(
    rows: list[dict[str, object]],
    selector_routes: list[dict[str, object]],
) -> str:
    activation_payload = pprint.pformat(rows, width=100, sort_dicts=False)
    route_payload = pprint.pformat(selector_routes, width=100, sort_dicts=False)
    return (
        '"""Generated mirror of native equilibrium activation metadata."""\n\n'
        "from __future__ import annotations\n\n"
        "# Generated by scripts/dev/generate_equilibrium_activation.py from native C++ metadata.\n"
        f"EQUILIBRIUM_ACTIVATION_MATRIX = {activation_payload}\n\n"
        f"EQUILIBRIUM_SELECTOR_ROUTE_CONTRACTS = {route_payload}\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the tracked mirror is stale")
    args = parser.parse_args(argv)

    rendered = _render(*_load_native_metadata())
    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != rendered:
            print(f"{OUTPUT.relative_to(REPO_ROOT)} is stale", file=sys.stderr)
            return 1
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
