"""Generate the Python mirror of the native equilibrium activation matrix."""

from __future__ import annotations

import argparse
import os
import pprint
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = REPO_ROOT / "src"
OUTPUT = (
    REPO_ROOT
    / "packages"
    / "epcsaft-equilibrium"
    / "src"
    / "epcsaft_equilibrium"
    / "equilibrium_activation.py"
)


def _load_native_rows() -> list[dict[str, object]]:
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    if str(SRC_ROOT) not in sys.path:
        sys.path.insert(0, str(SRC_ROOT))

    from scripts.dev.native_runtime_env import apply_native_runtime_env

    apply_native_runtime_env(os.environ)
    from epcsaft import _core

    return [dict(row) for row in _core._native_equilibrium_activation_matrix()]


def _render(rows: list[dict[str, object]]) -> str:
    payload = pprint.pformat(rows, width=100, sort_dicts=False)
    return (
        '"""Generated mirror of the native equilibrium activation matrix."""\n\n'
        "from __future__ import annotations\n\n"
        "# Generated by scripts/dev/generate_equilibrium_activation.py from native C++ metadata.\n"
        f"EQUILIBRIUM_ACTIVATION_MATRIX = {payload}\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the tracked mirror is stale")
    args = parser.parse_args(argv)

    rendered = _render(_load_native_rows())
    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != rendered:
            print(f"{OUTPUT.relative_to(REPO_ROOT)} is stale", file=sys.stderr)
            return 1
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
