from __future__ import annotations

from typing import Any


class ActivityCoefficientNative: ...


class CompositionContributionResult: ...


class CompressibilityFactorResult: ...


class FugacityContributionResult: ...


class NativeArgs: ...


class NativeMixture: ...


class NativeSolutionError(RuntimeError): ...


class NativeState: ...


class NativeValueError(ValueError): ...


class ResidualChemicalPotentialResult: ...


class ScalarContributionTerms: ...


class VectorContributionTerms: ...


def _native_association_site_fraction_solve(*args: Any, **kwargs: Any) -> Any: ...
def _native_cppad_eos_contributions(*args: Any, **kwargs: Any) -> Any: ...
def _native_cppad_neutral_binary_kij_properties(*args: Any, **kwargs: Any) -> Any: ...
def _native_cppad_neutral_binary_pair_properties(*args: Any, **kwargs: Any) -> Any: ...
def _native_cppad_association_component_parameters(*args: Any, **kwargs: Any) -> Any: ...
def _native_cppad_pressure_density(*args: Any, **kwargs: Any) -> Any: ...
def _native_cppad_pure_neutral_parameters(*args: Any, **kwargs: Any) -> Any: ...
def _native_cppad_smoke(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def _native_phase_state_ln_fugacity_composition_sensitivity(*args: Any, **kwargs: Any) -> Any: ...
def _native_provider_sdk_contract(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def __getattr__(name: str) -> Any: ...
