from __future__ import annotations

from typing import Any


class ActivityCoefficientNative: ...


class CompositionContributionResult: ...


class CompressibilityFactorResult: ...


class FugacityContributionResult: ...


class NativeArgs: ...


class NativeMixture: ...


class NativeSolutionError(RuntimeError): ...


class NativeState: ...


class NativeValueError(ValueError): ...


class ResidualChemicalPotentialResult: ...


class ScalarContributionTerms: ...


class VectorContributionTerms: ...


def _evaluate_generic_native_debug(*args: Any, **kwargs: Any) -> Any: ...
def _fit_generic_native_ceres(*args: Any, **kwargs: Any) -> Any: ...
def _fit_pure_neutral_native_ceres(*args: Any, **kwargs: Any) -> Any: ...
def _fit_pure_neutral_native_debug(*args: Any, **kwargs: Any) -> Any: ...
def _native_association_mass_action_block(*args: Any, **kwargs: Any) -> Any: ...
def _native_association_site_fraction_solve(*args: Any, **kwargs: Any) -> Any: ...
def _native_ceres_smoke(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def _native_cppad_eos_contributions(*args: Any, **kwargs: Any) -> Any: ...
def _native_cppad_neutral_binary_kij_properties(*args: Any, **kwargs: Any) -> Any: ...
def _native_cppad_neutral_binary_pair_properties(*args: Any, **kwargs: Any) -> Any: ...
def _native_cppad_pressure_density(*args: Any, **kwargs: Any) -> Any: ...
def _native_cppad_pure_neutral_parameters(*args: Any, **kwargs: Any) -> Any: ...
def _native_cppad_smoke(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def _native_electrolyte_contribution_block(*args: Any, **kwargs: Any) -> Any: ...
def _native_eos_phase_block(*args: Any, **kwargs: Any) -> Any: ...
def _native_eos_phase_system(*args: Any, **kwargs: Any) -> Any: ...
def _native_equilibrium_activation_matrix(*args: Any, **kwargs: Any) -> Any: ...
def _native_equilibrium_selector_contract(*args: Any, **kwargs: Any) -> Any: ...
def _native_equilibrium_selector_route_result(*args: Any, **kwargs: Any) -> Any: ...
def _native_ideal_reaction_smoke(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def _native_ipopt_quadratic_smoke(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def _native_ipopt_smoke(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def _native_neutral_two_phase_eos_nlp_contract(*args: Any, **kwargs: Any) -> Any: ...
def _native_neutral_two_phase_eos_postsolve(*args: Any, **kwargs: Any) -> Any: ...
def _native_neutral_two_phase_eos_result(*args: Any, **kwargs: Any) -> Any: ...
def _native_phase_state_ln_fugacity_composition_sensitivity(*args: Any, **kwargs: Any) -> Any: ...
def _native_second_order_assembly_smoke(*args: Any, **kwargs: Any) -> Any: ...
def __getattr__(name: str) -> Any: ...
